package:
  name: botocore
  version: "1.4.93"

source:
  fn: botocore-1.4.93.tar.gz
  url: https://pypi.python.org/packages/75/2b/5db4c3961b9dd8315b2e656e3fbc917cb0b5f6b3ec93b42f2894fa80f245/botocore-1.4.93.tar.gz
  md5: a871fd80457d81488f3e193f788e0089
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - botocore = botocore:main
    #
    # Would create an entry point called botocore that calls botocore.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10

  run:
    - python
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10

test:
  # Python imports
  imports:
    - botocore
    - botocore.docs
    - botocore.docs.bcdoc
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.chardet
    - botocore.vendored.requests.packages.urllib3
    - botocore.vendored.requests.packages.urllib3.contrib
    - botocore.vendored.requests.packages.urllib3.packages
    - botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname
    - botocore.vendored.requests.packages.urllib3.util

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/boto/botocore
  license: Apache Software License
  summary: 'Low-level, data-driven core of boto 3.'
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
